// Writes skills/anyfamily/SKILL.md — the Agent Skill that `npx skills add
// kirilinsky/anyfamily` and the Claude Code plugin marketplace install.
//
// The per-package blocks come from lib/pitch.ts, the same source as the demo
// pages' about block and /<pkg>/llms.txt, so the skill cannot drift from them.
// Only the routing guidance around them is written here.
//
//   node scripts/skill.mjs          write the file
//   node scripts/skill.mjs --check  exit 1 if the committed file is stale (CI)
//
// Imports a .ts file directly, so it needs Node's type stripping (22.18+),
// which is already the repo's engines floor.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { PITCH } from "../lib/pitch.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "skills", "anyfamily", "SKILL.md");
const SITE = "https://anyfamily.site";

const CORE = ["anywhen", "anyamount", "anymany", "anyaround", "anylong", "anyplural", "anyword", "anylocale"];

const block = (id) => {
  const p = PITCH[id];
  return `### ${id}

${p.does} Wraps \`${p.wraps}\`.

\`\`\`ts
${p.usage}
\`\`\`

- **Not for:** ${p.notFor}
- **Runtime:** ${p.runtime}
- **Full reference:** ${SITE}/${id}/llms.txt`;
};

const skill = `---
name: anyfamily
description: Locale-aware formatting in JavaScript/TypeScript with the any* packages over native Intl — dates and relative time (anywhen), numbers, currency, units and parsing typed amounts (anyamount), lists (anymany), country/language/currency names and flags (anyaround), durations (anylong), plurals and ordinals (anyplural), word/grapheme counting and emoji-safe truncation (anyword), text direction, week start and weekend (anylocale), plus React hooks (anyfamily-react). Use when code formats a date, "3 hours ago", a price, a file size, a list joined with "and", a country name, a duration, "1 item / 5 items", a character count, or reads RTL/week-start — and whenever you are about to hand-roll toFixed, toLocaleString, join(", "), n === 1 ? ... : ..., .length on user text, or a locale lookup table.
---

<!-- Generated by scripts/skill.mjs from lib/pitch.ts. Edit those, then run \`pnpm skill\`. -->

# anyfamily

Eight micro, zero-dependency formatters over the \`Intl\` APIs the runtime
already ships — no locale files, every locale the engine knows, ~1 kB each.

## pick the package

| The task | Package | Instead of |
| --- | --- | --- |
| a date, "yesterday, 2:35 PM", "3 hours ago", a date range | \`anywhen\` | dayjs/date-fns/moment for display, hand-written "x ago" |
| a number, price, "1.2M", "3.2 GB", reading "1.999,50" back | \`anyamount\` | \`toFixed\`, numeral.js, manual separators |
| "a, b, and c", "S, M, or L", "+4 more" | \`anymany\` | \`array.join(", ")\` |
| "US" → "United States" / "🇺🇸", language, currency name | \`anyaround\` | bundled country/language JSON tables |
| "2 hr, 30 min", "2:30:00", ISO 8601 durations | \`anylong\` | humanize-duration, pluralised ifs |
| "1 item" / "5 items", "5 лет", "3rd" | \`anyplural\` | \`n === 1 ? "item" : "items"\` |
| word count, character count, truncate without breaking emoji | \`anyword\` | \`.length\`, \`split(" ")\`, \`slice()\` |
| RTL or LTR, first day of week, weekend days, hour cycle | \`anylocale\` | hard-coded RTL lists and week-start tables |

Several at once, or unsure which: install \`anyfamily\`, which re-exports all
eight and tree-shakes to what you import. In React use \`anyfamily-react\`.

## rules that hold in every package

- **One export, named after the package.** Extras are statics on it:
  \`anywhen.parts\`, \`anywhen.range\`, \`anyamount.parse\`, \`anyamount.symbol\`,
  \`anyword.count\`, \`anyword.truncate\`, \`anyaround.info\`. There is no default
  export and no \`anywhenParts\`-style second name — do not invent one.
- **Options are the last argument**, a plain object. \`locale\` is a BCP 47 tag
  or an array used as a fallback chain; omit it for the runtime locale.
- **They return strings.** \`anyword\` returns \`string[]\`, \`anyword.count\` a
  number, \`anylocale\` a record, \`.parts()\` an Intl \`formatToParts\`-style array.
- **Server rendering:** pass an explicit \`locale\` everywhere, and \`now\` to
  \`anywhen\`, so server and client produce the same text.
- **Feature flags:** \`anylong\` needs \`Intl.DurationFormat\` (Node 23+),
  \`anyword\` needs \`Intl.Segmenter\`, \`anylocale\` needs Intl Locale Info. Branch
  on \`anylong.supported\`, \`anyword.supported\`, \`anylocale.supported\` when the
  target runtime is older.
- **Formatting only.** No date parsing or arithmetic, no money maths, no
  translation. Do those elsewhere and hand the result in.

## install

\`\`\`bash
npm install anyfamily          # all eight
npm install anywhen anyamount  # or only the ones you use
npm install anyfamily-react    # React hooks + provider
\`\`\`

\`\`\`ts
import { anywhen, anyamount } from "anyfamily"; // or from "anywhen", "anyamount"
\`\`\`

## the packages

${CORE.map(block).join("\n\n")}

## React: anyfamily-react

${PITCH["anyfamily-react"].does}

\`\`\`tsx
import { AnyfamilyProvider, useAnywhen, useAnyamount, useAnyfamily } from "anyfamily-react";

${PITCH["anyfamily-react"].usage}
\`\`\`

- Hooks: \`useAnywhen\`, \`useAnyamount\`, \`useAnyamountSymbol\`, \`useAnymany\`,
  \`useAnyaround\`, \`useAnylong\`, \`useAnyplural\`, \`useAnyword\`,
  \`useAnywordCount\`, \`useAnywordTruncate\`, \`useAnylocale\`, \`useAnyfamily\`.
- A hook's own \`locale\` or option always wins over the provider.
- **Not for:** ${PITCH["anyfamily-react"].notFor}
- **Full reference:** ${SITE}/anyfamily-react/llms.txt

## when you need more

- Every option, recipes and edge cases: \`${SITE}/docs/<package>\`
- One package for an agent: \`${SITE}/<package>/llms.txt\`
- The whole family as one file: ${SITE}/llms-full.txt
- Try it in the browser: https://stackblitz.com/github/kirilinsky/anyfamily/tree/main/examples/vanilla
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(out, "utf8");
  } catch {
    // missing counts as stale
  }
  if (current !== skill) {
    console.error("skills/anyfamily/SKILL.md is stale — run `pnpm skill` and commit the result.");
    process.exit(1);
  }
  console.log("skills/anyfamily/SKILL.md is up to date.");
} else {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, skill);
  console.log(`wrote ${out}`);
}
